### ISSUE TITLE
Syntax Errors?

### ISSUE THREAD

**Issue by rlzevallos** [petronny/pvz_converter#2]
Hi there, thanks for posting this utility! I am trying to convert my PVZ game of the year steam cloud save (that got converted to MacOS I assume when I ran my game on my macbook) back to Windows but I'm having some trouble understanding the instructions.

I installed python for windows, downloaded the repo to a folder in my documents folder, copied my user1.dat from the 3590 folder, then in cmd in the folder I ran `python convert.py windows user1.dat` which gave me 
```
File "convert.py", line 1
    Plants vs. Zombies Game of the Year.app/Contents/MacOS/convert.py
            ^
SyntaxError: invalid syntax
```

I tried the same thing in the Contents/MacOS folder and got another syntax error
```
File "convert.py", line 40
    print '%02x' %ord(bytes[i]),
               ^
SyntaxError: invalid syntax
```

Is there a particular folder I need to place the repo files into before running it? Or perhaps a different version of python? I downloaded the latest, Python 3.7.2.

Thank you!

**Comment by petronny** [comment]
Hi, since the default Python on mac is Python 2.7.
So this tool is programmed in Python 2.
You can try `python2 convert.py windows user1.dat`.

**Comment by jchen4230** [comment]
I've run convert.py on python2, converting a Mac save into a Windows save, but I get `Incorrect input format` error no matter what I put for the first argument. Is my save beyond saving?

**Comment by petronny** [comment]
@jchen4230 I'll follow the issue in #3
