### ISSUE TITLE
Incorrect input format

### ISSUE THREAD

**Issue by martinleopold** [petronny/pvz_converter#3]
Hey, 
running ```python convert.py windows user1.dat``` on the attached user data gives the error:
```
Incorrect input format
```
This apparently is a save from Mac. Anything that can be done?

[pvz save mac.zip](https://github.com/user-attachments/files/15511243/pvz.save.mac.zip)

**Comment by petronny** [comment]
Hi, it seems that the reason to this issue is that you have created one zombatar.
The current version doesn't support zombatar so you can try removing it.

**Comment by martinleopold** [comment]
Hey thanks for the quick reply. Unfortunately we can't change the save since, PVZ does't run on the current version of macOS anymore (no 64-bit support)...

**Comment by petronny** [comment]
In that case, you can try replacing all the `0x44` in `convert.py` to `0x8c`, which should support exactly one zombatar.

Below is the converted `user1.dat` but I forget how to import it on Windows.

[user1.zip](https://github.com/user-attachments/files/15517353/user1.zip)

**Comment by petronny** [comment]
> Below is the converted `user1.dat` but I forget how to import it on Windows.

I have found the right location which is `C:\Program Files (x86)\Steam\userdata\${user_id}\3590\remote`.

Place `user1.dat` here and the game can successfully load your zen garden on my machine.

**Comment by martinleopold** [comment]
Great, thx! In the meantime I managed the fix myself. I opened a pull request, which should add support for zombatars, by copying everything from the original file after the plants section.
